name: ${project.artifactId}
main: me.thebmanswan541.SurvivalGames.SurvivalGames
version: ${project.version}
author: [TheBmanSwan]
depend: [WorldEdit]
commands:
    sg:
      description: Default SurvivalGames command.
      usage: /<command>